# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            genkistation
tagline:          'one frame movies I'
description:      'one frame movies'
url:              https://genkistation.github.io/photography/
baseurl:          /photography/

author:
  name:           'genkistation'
  url:            https://genkistation.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://genkistation.github.io/photography
